"""Add Lease and LeaseAgreementTemplate models and relationships

Revision ID: 4f334650b26f
Revises: d1309f8c5d6c
Create Date: 2025-04-05 08:32:24.928466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f334650b26f'
down_revision: Union[str, None] = 'd1309f8c5d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.drop_index('ix_property_images_id')
        batch_op.drop_index('ix_property_images_property_id')

    op.drop_table('property_images')
    with op.batch_alter_table('verification_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_documents_document_type')
        batch_op.drop_index('ix_verification_documents_id')
        batch_op.drop_index('ix_verification_documents_property_id')
        batch_op.drop_index('ix_verification_documents_uploader_id')

    op.drop_table('verification_documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_id')
        batch_op.drop_index('ix_users_phone_number')

    op.drop_table('users')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index('ix_chats_id')
        batch_op.drop_index('ix_chats_initiator_id')
        batch_op.drop_index('ix_chats_property_id')
        batch_op.drop_index('ix_chats_property_user_id')

    op.drop_table('chats')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_chat_id')
        batch_op.drop_index('ix_chat_messages_id')
        batch_op.drop_index('ix_chat_messages_sender_id')

    op.drop_table('chat_messages')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_agent_id')
        batch_op.drop_index('ix_reviews_id')
        batch_op.drop_index('ix_reviews_reviewer_id')

    op.drop_table('reviews')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index('ix_properties_city')
        batch_op.drop_index('ix_properties_country')
        batch_op.drop_index('ix_properties_id')
        batch_op.drop_index('ix_properties_lister_id')
        batch_op.drop_index('ix_properties_owner_id')
        batch_op.drop_index('ix_properties_price')
        batch_op.drop_index('ix_properties_pricing_type')
        batch_op.drop_index('ix_properties_promotion_expires_at')
        batch_op.drop_index('ix_properties_state')
        batch_op.drop_index('ix_properties_status')

    op.drop_table('properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('lister_id', sa.CHAR(length=32), nullable=False),
    sa.Column('owner_id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('property_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('pricing_type', sa.VARCHAR(length=14), nullable=False),
    sa.Column('custom_rental_duration_days', sa.INTEGER(), nullable=True),
    sa.Column('bedrooms', sa.INTEGER(), nullable=True),
    sa.Column('bathrooms', sa.INTEGER(), nullable=True),
    sa.Column('square_feet', sa.INTEGER(), nullable=True),
    sa.Column('is_promoted', sa.BOOLEAN(), nullable=False),
    sa.Column('promotion_expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('rejected_at', sa.DATETIME(), nullable=True),
    sa.Column('rented_at', sa.DATETIME(), nullable=True),
    sa.Column('verification_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['lister_id'], ['users.id'], name='fk_properties_lister_id_users'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_properties_owner_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_properties')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index('ix_properties_status', ['status'], unique=False)
        batch_op.create_index('ix_properties_state', ['state'], unique=False)
        batch_op.create_index('ix_properties_promotion_expires_at', ['promotion_expires_at'], unique=False)
        batch_op.create_index('ix_properties_pricing_type', ['pricing_type'], unique=False)
        batch_op.create_index('ix_properties_price', ['price'], unique=False)
        batch_op.create_index('ix_properties_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('ix_properties_lister_id', ['lister_id'], unique=False)
        batch_op.create_index('ix_properties_id', ['id'], unique=False)
        batch_op.create_index('ix_properties_country', ['country'], unique=False)
        batch_op.create_index('ix_properties_city', ['city'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('reviewer_id', sa.CHAR(length=32), nullable=False),
    sa.Column('agent_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_review_rating_check'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name='fk_reviews_agent_id_users'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name='fk_reviews_reviewer_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_reviews'),
    sa.UniqueConstraint('reviewer_id', 'agent_id', name='uq_review_per_agent')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_reviewer_id', ['reviewer_id'], unique=False)
        batch_op.create_index('ix_reviews_id', ['id'], unique=False)
        batch_op.create_index('ix_reviews_agent_id', ['agent_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('chat_id', sa.CHAR(length=32), nullable=False),
    sa.Column('sender_id', sa.CHAR(length=32), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='fk_chat_messages_chat_id_chats'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='fk_chat_messages_sender_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_chat_messages')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_sender_id', ['sender_id'], unique=False)
        batch_op.create_index('ix_chat_messages_id', ['id'], unique=False)
        batch_op.create_index('ix_chat_messages_chat_id', ['chat_id'], unique=False)

    op.create_table('chats',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('property_id', sa.CHAR(length=32), nullable=True),
    sa.Column('initiator_id', sa.CHAR(length=32), nullable=False),
    sa.Column('property_user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], name='fk_chats_initiator_id_users'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_chats_property_id_properties'),
    sa.ForeignKeyConstraint(['property_user_id'], ['users.id'], name='fk_chats_property_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_chats')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index('ix_chats_property_user_id', ['property_user_id'], unique=False)
        batch_op.create_index('ix_chats_property_id', ['property_id'], unique=False)
        batch_op.create_index('ix_chats_initiator_id', ['initiator_id'], unique=False)
        batch_op.create_index('ix_chats_id', ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('reputation_points', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('is_verified_agent', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('profile_picture_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_phone_number', ['phone_number'], unique=1)
        batch_op.create_index('ix_users_id', ['id'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=1)

    op.create_table('verification_documents',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('property_id', sa.CHAR(length=32), nullable=False),
    sa.Column('uploader_id', sa.CHAR(length=32), nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=21), nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=512), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_verification_documents_property_id_properties'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='fk_verification_documents_uploader_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_verification_documents')
    )
    with op.batch_alter_table('verification_documents', schema=None) as batch_op:
        batch_op.create_index('ix_verification_documents_uploader_id', ['uploader_id'], unique=False)
        batch_op.create_index('ix_verification_documents_property_id', ['property_id'], unique=False)
        batch_op.create_index('ix_verification_documents_id', ['id'], unique=False)
        batch_op.create_index('ix_verification_documents_document_type', ['document_type'], unique=False)

    op.create_table('property_images',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('property_id', sa.CHAR(length=32), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=512), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_property_images_property_id_properties'),
    sa.PrimaryKeyConstraint('id', name='pk_property_images')
    )
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.create_index('ix_property_images_property_id', ['property_id'], unique=False)
        batch_op.create_index('ix_property_images_id', ['id'], unique=False)

    op.create_table('favorites',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('property_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_favorites_property_id_properties', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorites_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'property_id', name='pk_favorites'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_user_property_favorite')
    )
    # ### end Alembic commands ###
